FISH_RARITY = {
    "common": {
        "psyduck": {"dex": 54},
        "poliwag": {"dex": 60},
        "seel": {"dex": 86},
        "shellder": {"dex": 90},
        "krabby": {"dex": 98},
        "horsea": {"dex": 116},
        "goldeen": {"dex": 118},
        "magikarp": {"dex": 129},
        "staryu": {"dex": 120},
        "arrokuda": {"dex": 846},
        "barboach": {"dex": 339},
        "chinchou": {"dex": 170},
        "wooper": {"dex": 194},
        "ducklett": {"dex": 580},
        "lotad": {"dex": 270},
        "wingull": {"dex": 278},
        "surskit": {"dex": 283},
        "wailmer": {"dex": 320},
        "corphish": {"dex": 341},
        "spheal": {"dex": 363},
        "clamperl": {"dex": 366},
        "buizel": {"dex": 418},
        "finneon": {"dex": 456},
    },
    "uncommon": {
        "golduck": {"dex": 55},
        "poliwhirl": {"dex": 61},
        "tentacool": {"dex": 72},
        "slowpoke": {"dex": 79},
        "seadra": {"dex": 117},
        "omanyte": {"dex": 138},
        "kabuto": {"dex": 140},
        "marill": {"dex": 183},
        "quagsire": {"dex": 195},
        "bruxish": {"dex": 779},
        "clauncher": {"dex": 692},
        "binacle": {"dex": 688},
        "swanna": {"dex": 581},
        "frillish": {"dex": 592},
        "basculin": {"dex": 550},
        "tirtouga": {"dex": 564},
        "luvdisc": {"dex": 370},
        "bibarel": {"dex": 400},
        "sealeo": {"dex": 364},
        "whiscash": {"dex": 340},
        "crawdaunt": {"dex": 342},
        "feebas": {"dex": 349},
        "remoraid": {"dex": 223},
        "qwilfish": {"dex": 211},
        "lombre": {"dex": 271},
        "pelipper": {"dex": 279},
        "carvanha": {"dex": 318},
        "shellos": {"dex": 422},
        "panpour": {"dex": 515},
        "tympole": {"dex": 535},
    },
    "rare": {
        "poliwrath": {"dex": 62},
        "corsola": {"dex": 222},
        "huntail": {"dex": 367},
        "gorebyss": {"dex": 368},
        "floatzel": {"dex": 419},
        "tentacruel": {"dex": 73},
        "slowbro": {"dex": 80},
        "dewgong": {"dex": 87},
        "cloyster": {"dex": 91},
        "kingler": {"dex": 99},
        "starmie": {"dex": 121},
        "gyarados": {"dex": 130},
        "relicanth": {"dex": 369},
        "barraskewda": {"dex": 847},
        "seaking": {"dex": 119},
        "lanturn": {"dex": 171},
        "azumarill": {"dex": 184},
        "politoed": {"dex": 186},
        "slowking": {"dex": 199},
        "wishiwashi": {"dex": 746},
        "clawitzer": {"dex": 693},
        "barbaracle": {"dex": 689},
        "alomomola": {"dex": 594},
        "jellicent": {"dex": 593},
        "gastrodon": {"dex": 423},
        "simipour": {"dex": 516},
        "palpitoad": {"dex": 536},
        "lumineon": {"dex": 457},
        "sharpedo": {"dex": 319},
        "ludicolo": {"dex": 272},
        "octillery": {"dex": 224},
        "mantine": {"dex": 226},
    },
    "superrare": {
        "eiscue": {"dex": 875},
        "lapras": {"dex": 131},
        "wailord": {"dex": 321},
        "milotic": {"dex": 350},
        "dracovish": {"dex": 882},
        "arctovish": {"dex": 883},
        "basculegion": {"dex": 902},
        "omastar": {"dex": 139},
        "kabutops": {"dex": 141},
        "carracosta": {"dex": 565},
        "walrein": {"dex": 365},
        "seismitoad": {"dex": 537},
        "kingdra": {"dex": 230},
    },
    "legendary": {
        "kyogre": {"dex": 382},
        "suicune": {"dex": 245},
    },
}
